/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simko_fiks;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import simko_user.form_komplainUser;

/**
 *
 * @author nikof
 */
public class Form_historyUser extends javax.swing.JFrame {

    /**
     * Creates new form User_History
     */
    public Form_historyUser() {
        initComponents();
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cb_filter = new javax.swing.JComboBox<>();
        link_history = new javax.swing.JLabel();
        link_beranda = new javax.swing.JLabel();
        link_komplain = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Tagihan", "ID Penghuni", "No. Kamar", "Tanggal Bayar", "Periode Tagihan", "Total Tagihan", "Waktu"
            }
        ));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 1420, 640));

        cb_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Tanggal Terbaru", "Tanggal Terlama", "Tagihan Terbesar", "Tagihan Terkecil" }));
        cb_filter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cb_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_filterActionPerformed(evt);
            }
        });
        getContentPane().add(cb_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 240, 140, 50));

        link_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_historyMouseClicked(evt);
            }
        });
        getContentPane().add(link_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 60));

        link_beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_berandaMouseClicked(evt);
            }
        });
        getContentPane().add(link_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 170, 60));

        link_komplain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_komplainMouseClicked(evt);
            }
        });
        getContentPane().add(link_komplain, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 170, 60));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/form_historyUser.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_filterActionPerformed
        // TODO add your handling code here:
        try{
          
            int filter = cb_filter.getSelectedIndex();

            java.sql.Connection conn = (Connection)config.configDB();

            Statement stm = conn.createStatement();
            String msql;
            if (filter == 1) {
                msql = "select tb_history_tagihan.id_tagihan, tb_history_tagihan.id_penghuni, tb_history_tagihan.kamar, tb_history_tagihan.tgl_bayar, tb_history_tagihan.periode_tagihan, tb_history_tagihan.total_tagihan, tb_history_tagihan.waktu from tb_history_tagihan join tb_tagihan on tb_history_tagihan.id_tagihan = tb_tagihan.id_tagihan where tb_history_tagihan.id_penghuni = 1 order by tb_history_tagihan.tgl_bayar asc";
            }
            else if (filter == 2){
                msql = "select tb_history_tagihan.id_tagihan, tb_history_tagihan.id_penghuni, tb_history_tagihan.kamar, tb_history_tagihan.tgl_bayar, tb_history_tagihan.periode_tagihan, tb_history_tagihan.total_tagihan, tb_history_tagihan.waktu from tb_history_tagihan join tb_tagihan on tb_history_tagihan.id_tagihan = tb_tagihan.id_tagihan where tb_history_tagihan.id_penghuni = 1 order by tb_history_tagihan.tgl_bayar desc";
            }
            else if (filter == 3){
                msql = "select tb_history_tagihan.id_tagihan, tb_history_tagihan.id_penghuni, tb_history_tagihan.kamar, tb_history_tagihan.tgl_bayar, tb_history_tagihan.periode_tagihan, tb_history_tagihan.total_tagihan, tb_history_tagihan.waktu from tb_history_tagihan join tb_tagihan on tb_history_tagihan.id_tagihan = tb_tagihan.id_tagihan where tb_history_tagihan.id_penghuni = 1 order by tb_history_tagihan.total_tagihan desc";
            }
            else{
                msql = "select tb_history_tagihan.id_tagihan, tb_history_tagihan.id_penghuni, tb_history_tagihan.kamar, tb_history_tagihan.tgl_bayar, tb_history_tagihan.periode_tagihan, tb_history_tagihan.total_tagihan, tb_history_tagihan.waktu from tb_history_tagihan join tb_tagihan on tb_history_tagihan.id_tagihan = tb_tagihan.id_tagihan where tb_history_tagihan.id_penghuni = 1 order by tb_history_tagihan.total_tagihan asc";
            }
            System.out.println(msql);
            ResultSet result = stm.executeQuery(msql);
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID Tagihan");
            tbl.addColumn("ID Penghuni");
            tbl.addColumn("No. Kamar");
            tbl.addColumn("Tanggal Bayar");
            tbl.addColumn("Periode Tagihan");
            tbl.addColumn("Total Tagihan");
            tbl.addColumn("Waktu");
            jTable1.setModel(tbl);

            while (result.next()){
                tbl.addRow(new Object[]{
                    result.getString("tb_history_tagihan.id_tagihan"),
                    result.getString("tb_history_tagihan.id_penghuni"),
                    result.getString("tb_history_tagihan.kamar"),
                    result.getString("tb_history_tagihan.tgl_bayar"),
                    result.getString("tb_history_tagihan.periode_tagihan"),
                    result.getString("tb_history_tagihan.total_tagihan"),
                    result.getString("tb_history_tagihan.waktu")
                });
                jTable1.setModel(tbl);
            }

        } catch (SQLException ex) {
            Logger.getLogger(form_kamar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cb_filterActionPerformed

    private void link_komplainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_komplainMouseClicked
        // TODO add your handling code here:
        new form_komplainUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_link_komplainMouseClicked

    private void link_berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_berandaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_link_berandaMouseClicked

    private void link_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_historyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_link_historyMouseClicked
    public void getData(){
        try{
            java.sql.Connection conn = (Connection)config.configDB();
            Statement stm = conn.createStatement();
            ResultSet result = stm.executeQuery("select tb_history_tagihan.id_tagihan, tb_history_tagihan.id_penghuni, tb_history_tagihan.kamar, tb_history_tagihan.tgl_bayar, tb_history_tagihan.periode_tagihan, tb_history_tagihan.total_tagihan, tb_history_tagihan.waktu from tb_history_tagihan join tb_tagihan on tb_history_tagihan.id_tagihan = tb_tagihan.id_tagihan where tb_history_tagihan.id_penghuni = 1");
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            //reset
            model.setRowCount(0);
            while(result.next()) {
               String id_tagihan = result.getString("tb_history_tagihan.id_tagihan");
               String id_penghuni = result.getString("tb_history_tagihan.id_penghuni");
               String no_kamar = result.getString("tb_history_tagihan.kamar");
               String tgl_bayar = result.getString("tb_history_tagihan.tgl_bayar");
               String periode_tagihan = result.getString("tb_history_tagihan.periode_tagihan");
               String total_tagihan = result.getString("tb_history_tagihan.total_tagihan");
               String waktu = result.getString("tb_history_tagihan.waktu");
               
               model.addRow(new Object[]{
                   id_tagihan,
                   id_penghuni,
                   no_kamar,
                   tgl_bayar,
                   periode_tagihan,
                   total_tagihan,
                   waktu
                   
               });
               
            }
             
            
        } catch (SQLException ex) {
            Logger.getLogger(form_kamar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_historyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_historyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_historyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_historyUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_historyUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> cb_filter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel link_beranda;
    private javax.swing.JLabel link_history;
    private javax.swing.JLabel link_komplain;
    // End of variables declaration//GEN-END:variables
}
