/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simko_fiks;

import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Farhan Ariyanto
 */
public class lupapassword1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public lupapassword1() {
        initComponents();
        addplaceholderstyle(tf_username);
        addplaceholderstyle1(tf_password);
        addplaceholderstyle1(tf_konpassword);
        this.icon1.setVisible(false);
        this.icon3.setVisible(false);
        
        pop_up_ubahPass.setVisible(false);
        pop_up_ubahPass.setBackground(new Color(0,0,0,0));
    }
    
    public void addplaceholderstyle(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.gray);
        
    }
    
    public void addplaceholderstyle1(JTextField textField){
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
        
    }
    
    public void removeplaceholderstyle (JTextField textField) {
        Font font= textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_up_ubahPass = new javax.swing.JPanel();
        btn_oke = new javax.swing.JLabel();
        btnX = new javax.swing.JLabel();
        bg_ubahPass = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        tf_password = new javax.swing.JPasswordField();
        tf_konpassword = new javax.swing.JPasswordField();
        btn_batal = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        pop_up_ubahPass.setBackground(new java.awt.Color(0, 0, 0));
        pop_up_ubahPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_oke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okeMouseClicked(evt);
            }
        });
        pop_up_ubahPass.add(btn_oke, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 575, 120, 35));

        btnX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXMouseClicked(evt);
            }
        });
        pop_up_ubahPass.add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 429, 31, 31));

        bg_ubahPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/popup_berhasilUbahPass.png"))); // NOI18N
        pop_up_ubahPass.add(bg_ubahPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 418, 511, 243));

        getContentPane().add(pop_up_ubahPass);
        pop_up_ubahPass.setBounds(0, 10, 1920, 1080);

        tf_username.setBackground(new Color(0,0,0,0));
        tf_username.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        tf_username.setForeground(new java.awt.Color(153, 153, 153));
        tf_username.setText("masukkan NIK");
        tf_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tf_username.setOpaque(false);
        tf_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_usernameFocusLost(evt);
            }
        });
        getContentPane().add(tf_username);
        tf_username.setBounds(700, 390, 540, 70);

        tf_password.setBackground(new Color(0,0,0,0));
        tf_password.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        tf_password.setBorder(null);
        tf_password.setOpaque(false);
        tf_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_passwordFocusLost(evt);
            }
        });
        tf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(tf_password);
        tf_password.setBounds(690, 530, 550, 70);

        tf_konpassword.setBackground(new Color(0,0,0,0));
        tf_konpassword.setFont(new java.awt.Font("Microsoft Tai Le", 0, 36)); // NOI18N
        tf_konpassword.setBorder(null);
        tf_konpassword.setOpaque(false);
        tf_konpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_konpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_konpasswordFocusLost(evt);
            }
        });
        tf_konpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_konpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tf_konpassword);
        tf_konpassword.setBounds(690, 670, 570, 80);

        btn_batal.setForeground(new Color(0,0,0,0));
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn batal normal.png"))); // NOI18N
        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_batalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_batalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_batalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_batalMouseReleased(evt);
            }
        });
        getContentPane().add(btn_batal);
        btn_batal.setBounds(680, 810, 290, 80);

        btn_ubah.setForeground(new Color(0,0,0,0));
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn ubah normal.png"))); // NOI18N
        btn_ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ubahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ubahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ubahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_ubahMouseReleased(evt);
            }
        });
        getContentPane().add(btn_ubah);
        btn_ubah.setBounds(980, 810, 290, 80);

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/unhide.png"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon1MousePressed(evt);
            }
        });
        getContentPane().add(icon1);
        icon1.setBounds(1280, 540, 60, 50);

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide.png"))); // NOI18N
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon2MousePressed(evt);
            }
        });
        getContentPane().add(icon2);
        icon2.setBounds(1280, 540, 60, 54);

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/unhide.png"))); // NOI18N
        icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon3MousePressed(evt);
            }
        });
        getContentPane().add(icon3);
        icon3.setBounds(1280, 680, 60, 50);

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide.png"))); // NOI18N
        icon4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                icon4FocusGained(evt);
            }
        });
        icon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icon4MousePressed(evt);
            }
        });
        getContentPane().add(icon4);
        icon4.setBounds(1280, 680, 60, 54);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/form_lupa_password(revisi 2).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 0, 1920, 1080);

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_usernameFocusGained
        if(tf_username.getText().equals("masukkan NIK")){
            tf_username.setText(null);
            tf_username.requestFocus();
            removeplaceholderstyle(tf_username);
        }
    }//GEN-LAST:event_tf_usernameFocusGained

    private void tf_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_usernameFocusLost
        if(tf_username.getText().length()==0){

            addplaceholderstyle(tf_username);
            tf_username.setText("masukkan NIK");
        }
    }//GEN-LAST:event_tf_usernameFocusLost

    private void tf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passwordActionPerformed

    private void tf_konpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_konpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_konpasswordActionPerformed

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        this.setVisible(false);
        new frmlogin1().setVisible(true);
    }//GEN-LAST:event_btn_batalMouseClicked

    private void btn_batalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseEntered
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn batal entered.png")));
    }//GEN-LAST:event_btn_batalMouseEntered

    private void btn_batalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseExited
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn batal normal.png")));
    }//GEN-LAST:event_btn_batalMouseExited

    private void btn_ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseClicked
        if(tf_password.getText().equals("")){
                JOptionPane.showMessageDialog(null, "password baru tidak boleh kosong");
            }else if((tf_konpassword.getText().equals(""))){
                JOptionPane.showMessageDialog(null, "confirm password baru tidak boleh kosong");
            }else if(tf_username.getText().equals("")){
            JOptionPane.showMessageDialog(null, "nik tidak boleh kosong");  
            }
            else if(tf_konpassword.getText().equals(tf_password.getText())) {
                try{
                    java.sql.Connection conn = (Connection)config.configDB();
                    java.sql.Statement stm = conn.createStatement();
                    ResultSet rs = stm.executeQuery("select * from tb_login where nik = "+tf_username.getText()+"");
                        if(rs.next()){
                           try{
                               String sql = "update tb_login set passwords = '"+ tf_password.getText()
                                       +"' where nik = "+tf_username.getText()+"";
                               java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                                pst.execute();
                                pop_up_ubahPass.setVisible(true);                               
                           }catch(Exception e){
                               JOptionPane.showMessageDialog(null, "gagal ubah password");
                           }
                        }else{
                            JOptionPane.showMessageDialog(null, "nik tidak sesuai");
                        }
        //            pop_up_ubahPass.setVisible(true);
                    }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "nik salah" + e);
                    }
            }
            else{ JOptionPane.showMessageDialog(null, "masukkan nik atau password secara benar");
            }
    }//GEN-LAST:event_btn_ubahMouseClicked

    private void btn_ubahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseEntered
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn ubah entered.png")));
    }//GEN-LAST:event_btn_ubahMouseEntered

    private void btn_ubahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseExited
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn ubah normal.png")));
    }//GEN-LAST:event_btn_ubahMouseExited

    private void icon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MousePressed
        icon2.setVisible(true);
        icon1.setVisible(false);
        tf_password.setEchoChar('*');
    }//GEN-LAST:event_icon1MousePressed

    private void icon2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MousePressed
        icon1.setVisible(true);
        icon2.setVisible(false);
        tf_password.setEchoChar((char)0);
    }//GEN-LAST:event_icon2MousePressed

    private void tf_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_passwordFocusGained
        if(tf_password.getText().equals("masukkan password baru")){
            tf_password.setText(null);
            tf_password.requestFocus();
            removeplaceholderstyle(tf_password);
        }
    }//GEN-LAST:event_tf_passwordFocusGained

    private void tf_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_passwordFocusLost
        if(tf_password.getText().length()==0){

            addplaceholderstyle(tf_password);
            tf_password.setText("masukkan password baru");
        }
    }//GEN-LAST:event_tf_passwordFocusLost

    private void tf_konpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_konpasswordFocusGained
        if(tf_konpassword.getText().equals("confirm password baru")){
            tf_konpassword.setText(null);
            tf_konpassword.requestFocus();
            removeplaceholderstyle(tf_password);
        }
    }//GEN-LAST:event_tf_konpasswordFocusGained

    private void tf_konpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_konpasswordFocusLost
        if(tf_konpassword.getText().length()==0){

            addplaceholderstyle(tf_konpassword);
            tf_konpassword.setText("confirm password baru");
        }
    }//GEN-LAST:event_tf_konpasswordFocusLost

    private void icon4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MousePressed
        icon3.setVisible(true);
        icon4.setVisible(false);
        tf_konpassword.setEchoChar((char)0);

    }//GEN-LAST:event_icon4MousePressed

    private void icon3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MousePressed
        icon4.setVisible(true);
        icon3.setVisible(false);
        tf_konpassword.setEchoChar('*');
    }//GEN-LAST:event_icon3MousePressed

    private void icon4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_icon4FocusGained
        
    }//GEN-LAST:event_icon4FocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(lupapassword1.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void btn_ubahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMousePressed
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn ubah press.png")));
    }//GEN-LAST:event_btn_ubahMousePressed

    private void btn_ubahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseReleased
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn ubah entered.png")));
    }//GEN-LAST:event_btn_ubahMouseReleased

    private void btn_batalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMousePressed
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn batal press.png")));
    }//GEN-LAST:event_btn_batalMousePressed

    private void btn_batalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseReleased
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hover/btn batal entered.png")));
    }//GEN-LAST:event_btn_batalMouseReleased

    private void btn_okeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okeMouseClicked
        // TODO add your handling code here:
        pop_up_ubahPass.setVisible(false);
        new frmlogin1().setVisible(true);
    }//GEN-LAST:event_btn_okeMouseClicked

    private void btnXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseClicked
        // TODO add your handling code here:
        pop_up_ubahPass.setVisible(false);
        new frmlogin1().setVisible(true);
    }//GEN-LAST:event_btnXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupapassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupapassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupapassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupapassword1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lupapassword1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_ubahPass;
    private javax.swing.JLabel btnX;
    private javax.swing.JLabel btn_batal;
    private javax.swing.JLabel btn_oke;
    private javax.swing.JLabel btn_ubah;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pop_up_ubahPass;
    private javax.swing.JPasswordField tf_konpassword;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
