
package pop_up;


public class popup_berhasilTambah extends javax.swing.JFrame {

    /**
     * Creates new form popup_berhasil
     */
    public popup_berhasilTambah() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_oke = new javax.swing.JLabel();
        btnX = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        btn_oke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_oke);
        btn_oke.setBounds(190, 150, 130, 40);

        btnX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXMouseClicked(evt);
            }
        });
        getContentPane().add(btnX);
        btnX.setBounds(460, 10, 30, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/popup_berhasilTambah.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 510, 240);

        setSize(new java.awt.Dimension(511, 243));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okeMouseClicked
        
    }//GEN-LAST:event_btn_okeMouseClicked

    private void btnXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popup_berhasilTambah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnX;
    private javax.swing.JLabel btn_oke;
    // End of variables declaration//GEN-END:variables
}
