/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pop_up;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import simko_fiks.config;
import simko_fiks.form_kamar;
/**
 *
 * @author gilan
 */
public class popup_hapus extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public popup_hapus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnX = new javax.swing.JLabel();
        btn_oke = new javax.swing.JLabel();
        btn_batal = new javax.swing.JLabel();
        pop_up = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btnX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXMouseClicked(evt);
            }
        });
        getContentPane().add(btnX);
        btnX.setBounds(460, 10, 28, 28);

        btn_oke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_okeMouseClicked(evt);
            }
        });
        getContentPane().add(btn_oke);
        btn_oke.setBounds(260, 154, 122, 40);

        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        getContentPane().add(btn_batal);
        btn_batal.setBounds(130, 154, 122, 40);

        pop_up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/popup_hapus.png"))); // NOI18N
        getContentPane().add(pop_up);
        pop_up.setBounds(0, 0, 510, 240);

        setSize(new java.awt.Dimension(511, 243));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okeMouseClicked
        this.setVisible(false);
        new form_kamar().setVisible(true);
//        form_kamar FK = new form_kamar();
        /*
        try{
            int row = FP.tabelPenghuni.getSelectedRow();
            String Nama = FP.tabelPenghuni.getModel().getValueAt (row, 1).toString();
            String resultSet = "DELETE FROM tb_penghuni WHERE id_penghuni='"+Nama+"'";
            java.sql.Connection conn = (Connection)config.configDB();
            PreparedStatement pst = conn.prepareStatement(resultSet);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            this.dispose();
            FP.getData();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } */
       
//    try{
//        int row = FK.tabelPenghuni.getSelectedRow();
//        String id_penghuni = FP.tabelPenghuni.getModel().getValueAt(row, 0).toString();
//        String resultSet = "DELETE FROM tb_penghuni WHERE id_penghuni='"+id_penghuni+"'";
//        
//        java.sql.Connection conn = (Connection)config.configDB();
//        java.sql.PreparedStatement pst = conn.prepareStatement(resultSet);
//        pst.execute();
//        
//        JOptionPane.showMessageDialog(null, "Berhasil");
//        }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
       
    }//GEN-LAST:event_btn_okeMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_batalMouseClicked

    private void btnXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_hapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_hapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_hapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_hapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popup_hapus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnX;
    private javax.swing.JLabel btn_batal;
    private javax.swing.JLabel btn_oke;
    private javax.swing.JLabel pop_up;
    // End of variables declaration//GEN-END:variables
}
